---
title: "Exam"
output: markdowntemplates::minimal
---

```{r setup, include=FALSE, message=F, warning=F, error=F, comment=NA}
knitr::opts_chunk$set(echo=T, eval=T, message=F, warning=F, error=F, comment=NA)
```

## Article assigned

1. Exact tests via multiple data splitting (Aiello)

2. Testing the equality of multivariate means when $p>n$ by combining the Hotelling and Simes tests (Cogo)

3. Familywise error rate control by interactive unmasking (De Carolis)

4. Universal Inference (Bi)

5. Inference in Experiments with Matched Pairs (Barile)

6. Testing by betting: A strategy for statistical and scientific communication (Sartirana)

### Short paper submission

An abstract of less than 200 words and a short paper between 4 and 6 pages, summarising the assigned article, should be submitted via e-mail by Monday July 5th, h. 14:00. The short papers can be submitted using LaTeX or Word SIS editorial standards.

* LaTeX template (click [here](latex.zip) to download the Latex template)
* Word template (click [here](word.zip) to download the Word template)

Abstract in italian is not required. 

### Presentation

The assigned article will be presented on Monday July 12th starting at h. 14:00. The presentation can be based on slides, writing on a tablet, etc. Each presenting author will have 30 minutes (20 minutes for presentation, 10 minutes for answering questions). 


